export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  SERVICES: '/services',
  FEATURES: '/features',
  INDUSTRIES: '/industries',
  PRICING: '/pricing',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  CUSTOMER: {
    DASHBOARD: '/dashboard',
    CHAT: '/chat',
    CHAT_HISTORY: '/chat-history',
    DOCUMENTS: '/documents',
    PROFILE: '/profile',
    NOTIFICATIONS: '/notifications',
    FAQ: '/faq',
    TICKETS: '/tickets',
  },

  SUPER_ADMIN: {
    DASHBOARD: '/admin',
    ORGANIZATIONS: '/admin/organizations',
    USERS: '/admin/users',
    USER_DETAILS: '/admin/users/:id',
    ROLES: '/admin/roles',
    AUDIT_LOGS: '/admin/audit-logs',
    SUBSCRIPTIONS: '/admin/subscriptions',
    ORG_APPROVALS: '/admin/org-approvals',
    TOKEN_USAGE: '/admin/token-usage',
    AI_CONFIG: '/admin/ai-config',
    CONTENT: '/admin/content',
    SEARCH: '/admin/search',
  },

  ADMIN: {
    DASHBOARD: '/org-admin',
    USERS: '/org-admin/users',
    USER_DETAILS: '/org-admin/users/:id',
    DOCUMENTS: '/org-admin/documents',
    DOCUMENT_TYPES: '/org-admin/document-types',
    VERIFICATIONS: '/org-admin/document-verifications',
    CHATBOT: '/org-admin/chatbot',
    ANALYTICS: '/org-admin/ai-analytics',
    LOGS: '/org-admin/logs',
    FAQS: '/org-admin/faqs',
    CONVERSATIONS: '/org-admin/conversations',
    KNOWLEDGE_BASE: '/org-admin/knowledge-base',
  },

  SUPPORT: {
    DASHBOARD: '/support/dashboard',
    TICKETS: '/support/tickets',
    TICKET_DETAILS: '/support/tickets/:id',
    CHAT: '/support/chat',
    DOCUMENTS: '/support/documents',
    NOTIFICATIONS: '/support/notifications',
  },
} as const;
